### ISSUE TITLE
Load errors on Win 7 64Bit with 20110216 release

### ISSUE THREAD

**Issue by kayapo** [exvion/su2yafaray#1]
I use a SketcUp 8 (last release), Yafaray 0.1.1 Win 32 bit and after i started SketchUp get this error:

Error Loading File C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/su2yafaray/su2yafaray.rb
126: A megadott modul nem található.   - C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/su2yafaray/yafqt.soError Loading File su2yafaray_loader.rb
126: A megadott modul nem található.   - C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/su2yafaray/yafqt.so

"A megadott modul nem található." = "The specified module could not be found."

**Comment by exvion** [comment]
Delete folder C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/su2yafaray/
Delete file C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/su2yafaray.rb
Delete file C:/Program Files (x86)/Google/Google SketchUp 8/Plugins/su2yafaray_loader.rb
Try it https://github.com/exvion/su2yafaray/wiki/Installation
Try install Microsoft Visual C++ 2010 Redistributable Package (x64)
http://www.microsoft.com/downloads/en/details.aspx?FamilyID=bd512d9e-43c8-4655-81bf-9350143d5867

**Comment by kayapo** [comment]
After i remove old version of su2yafaray and install Microsofts Visual C++ 2010 Redist. the problem is not solved! :(

**Comment by exvion** [comment]
Where you get su2yafaray? What direct link?

**Comment by kayapo** [comment]
I used the links for your wiki page:
https://github.com/downloads/exvion/su2yafaray/su2yafaray-0.1.20110216.zip
